apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi
  name: fastapi
  namespace: sam-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: 192.168.1.110:8081/docker/fastapi
          ports:
            - containerPort: 8000
              name: "fastapi-http"
      # imagePullSecrets:
      #   - name: jfrogsecret
      restartPolicy: Always
